name: Build Docker Image 

on:
  workflow_dispatch:
    branches:
      - main 

env: 
  DOCKER_PASSWORD: ${{secrets.dockerhub_token}}

jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
    - name: Get Code
      uses: actions/checkout@v2

    - name: docker login 
      run: | 
        docker login -u rayanoh -p ${{env.DOCKER_PASSWORD}}

    - name: Build Image 
      run: |
        docker build -t Rayane59/Aston:latest . 
