name: Build Docker Image 

on:
  workflow_dispatch:
    branches:
      - main 

env: 
  DOCKER_PASSWORD: ${{secrets.dockerhub_token}}
  IMAGE_NAME: ${{ vars.IMAGE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: Get Code
      uses: actions/checkout@v2
  
    - name: docker login 
      run: | 
        docker login -u rayanoh -p ${{env.DOCKER_PASSWORD}}
        
    - name: Get Version
      run: |
          IMAGE_TAG=$(cat infos.json | jq -r '.["version"]')
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    - name: Build Image 
      run: |
        docker build -t rayanoh/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}} .
    
    - name: Docker Push
      run: |
          docker push rayano/${{ env.IMAGE_NAME}}:${{ env.IMAGE_TAG}}
